// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.0";

// src/lib/mcp/data.ts
var SERVICES = [
  {
    name: "Web Development",
    description: "High-performance web applications built with React, Next.js, and modern frameworks."
  },
  {
    name: "Mobile App",
    description: "Cross-platform mobile experiences with React Native and native-like performance."
  },
  {
    name: "3D & Interactive",
    description: "Immersive 3D web experiences using Three.js, WebGL, and custom shaders."
  },
  {
    name: "UI/UX Design",
    description: "User-centered design with prototyping, motion design, and design systems."
  },
  { name: "Full-Stack Project", description: "End-to-end product build, frontend through backend." },
  { name: "Consultation", description: "Advice session on architecture, performance, or design." }
];
var BOOKABLE_SERVICES = SERVICES.map((service) => service.name);
var PROJECTS = [
  {
    name: "Quantum Dashboard",
    description: "Real-time analytics platform with 3D data visualization and predictive AI insights.",
    tech: ["React", "Three.js", "Python", "AI"]
  },
  {
    name: "Neural Interface",
    description: "Brain-computer interface prototype for accessible web navigation using ML models.",
    tech: ["TensorFlow", "WebGL", "Node.js"]
  },
  {
    name: "Synthwave Studio",
    description: "Web-based music production tool with real-time audio processing and visual feedback.",
    tech: ["Web Audio", "Canvas", "React"]
  },
  {
    name: "CryptoVerse",
    description: "Decentralized portfolio tracker with animated charts and real-time market data.",
    tech: ["Solidity", "React", "D3.js"]
  }
];
var PROFILE = {
  name: "Areeb",
  role: "Developer \u2014 web, mobile, and interactive 3D experiences",
  email: "alliareeb650@gmail.com",
  phone: "033066528075",
  location: "North Karachi, Sector 11-C, Karachi, Pakistan",
  responseTime: "Usually replies within 24 hours"
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Areeb's public profile: role, public contact details, location, and typical response time.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${PROFILE.name} \u2014 ${PROFILE.role}
Email: ${PROFILE.email}
Phone: ${PROFILE.phone}
Location: ${PROFILE.location}
${PROFILE.responseTime}`
      }
    ],
    structuredContent: { profile: { ...PROFILE } }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the services Areeb offers and that can be booked.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: SERVICES.map((s) => `- ${s.name}: ${s.description}`).join("\n")
      }
    ],
    structuredContent: {
      services: SERVICES.map((s) => ({ name: s.name, description: s.description }))
    }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.0";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List the featured projects in Areeb's portfolio with their tech stacks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: PROJECTS.map(
          (p) => `- ${p.name} (${p.tech.join(", ")}): ${p.description}`
        ).join("\n")
      }
    ],
    structuredContent: {
      projects: PROJECTS.map((p) => ({
        name: p.name,
        description: p.description,
        tech: p.tech.map((t) => t)
      }))
    }
  })
});

// src/lib/mcp/tools/send-message.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z } from "npm:zod@3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/send-message.ts
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send a message",
  description: "Send Areeb a message through the portfolio contact form. Ask the sender for their real name and email first.",
  inputSchema: {
    name: z.string().trim().min(1).max(100).describe("Sender's full name."),
    email: z.string().trim().email().max(255).describe("Sender's email address."),
    subject: z.string().trim().min(1).max(200).describe("Short subject line."),
    message: z.string().trim().min(1).max(2e3).describe("Message body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, subject, message }) => {
    const { error } = await supabaseAnon().from("contact_submissions").insert({ name, email, subject, message });
    if (error) throw new ToolError(`Could not send the message: ${error.message}`);
    return {
      content: [
        {
          type: "text",
          text: `Message sent to Areeb. He usually replies within 24 hours at ${email}.`
        }
      ]
    };
  }
});

// src/lib/mcp/tools/request-booking.ts
import { defineTool as defineTool5, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z2 } from "npm:zod@3.25.76";
var request_booking_default = defineTool5({
  name: "request_booking",
  title: "Request a booking",
  description: "Request a service booking with Areeb on a chosen weekday. Use list_services first to pick a valid service name.",
  inputSchema: {
    full_name: z2.string().trim().min(1).max(100).describe("Requester's full name."),
    email: z2.string().trim().email().max(255).describe("Requester's email address."),
    phone: z2.string().trim().min(1).max(20).describe("Requester's phone number."),
    service: z2.string().trim().min(1).describe("One of the services from list_services."),
    booking_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Requested date as YYYY-MM-DD. Must be a future weekday."),
    message: z2.string().trim().max(1e3).optional().describe("Optional extra details.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ full_name, email, phone, service, booking_date, message }) => {
    if (!BOOKABLE_SERVICES.includes(service)) {
      throw new ToolError2(
        `Unknown service "${service}". Available services: ${BOOKABLE_SERVICES.join(", ")}.`
      );
    }
    const requested = /* @__PURE__ */ new Date(`${booking_date}T00:00:00Z`);
    if (Number.isNaN(requested.getTime())) throw new ToolError2("booking_date is not a valid date.");
    const today = /* @__PURE__ */ new Date();
    today.setUTCHours(0, 0, 0, 0);
    if (requested < today) throw new ToolError2("booking_date must be today or later.");
    const weekday = requested.getUTCDay();
    if (weekday === 0 || weekday === 6) {
      throw new ToolError2("Bookings are only available on weekdays (Monday to Friday).");
    }
    const { error } = await supabaseAnon().from("bookings").insert({
      full_name,
      email,
      phone,
      service,
      booking_date,
      message: message ?? null
    });
    if (error) throw new ToolError2(`Could not create the booking: ${error.message}`);
    return {
      content: [
        {
          type: "text",
          text: `Booking request for ${service} on ${booking_date} submitted. Areeb will confirm by email at ${email}.`
        }
      ],
      structuredContent: { booking: { full_name, email, service, booking_date } }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "astral-canvas",
  title: "Astral Canvas",
  version: "0.1.0",
  instructions: "Public tools for Areeb's developer portfolio. Use get_profile for contact details, list_services and list_projects to explore his work, send_message to contact him, and request_booking to reserve a weekday service slot. Always collect the person's real name, email, and (for bookings) phone number before submitting.",
  tools: [
    get_profile_default,
    list_services_default,
    list_projects_default,
    send_message_default,
    request_booking_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
